name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

      # (*) To add a file, add the following section for it
    - name: Probas Cheatsheet
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cheatsheet.tex
        latexmk_shell_escape: true
        working_directory: probas

    - name: IAS Cheatsheet
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: ias-cheatsheet

    - name: Probas Lectures
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: probas_amphi/fr
    - name: Probas Long Cheatsheet
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: probas_full_cheatsheet
        
    - name: Optimisation Full Cheatsheet
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: optimisation/cheatsheet_full/

    - name: Optimisation Cheatsheet
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: optimisation/cheatsheet/

    - name: Carathéodory Criterion Intuition En
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: measure-theory/explanations/carathedory-criterion/en/

    - name: Carathéodory Criterion Intuition Fr
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: measure-theory/explanations/carathedory-criterion/fr/

    - name: Integration Cheatsheet En
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: measure-theory/cheatsheet/en/

    - name: Integration Cheatsheet Fr
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: measure-theory/cheatsheet/fr/

    - name: Check PDF files
      run: |
        file probas/cheatsheet.pdf | grep -q ' PDF '
        file probas_full_cheatsheet/main.pdf | grep -q ' PDF '
        file ias-cheatsheet/main.pdf | grep -q ' PDF '
        file probas_amphi/fr/main.pdf | grep -q ' PDF '
        file optimisation/cheatsheet/main.pdf | grep -q ' PDF '
        file optimisation/cheatsheet_full/main.pdf | grep -q ' PDF '
        file measure-theory/explanations/carathedory-criterion/en/main.pdf | grep -q ' PDF '
        file measure-theory/explanations/carathedory-criterion/fr/main.pdf | grep -q ' PDF '
        file measure-theory/cheatsheet/en/main.pdf | grep -q ' PDF '
        file measure-theory/cheatsheet/fr/main.pdf | grep -q ' PDF '
        
    - name: Upload to GitHub pages
      run: |
        git config --global user.name "DobbiKov (auto)"
        git config --global user.email "dobbikov@gmail.com"

        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:dobbikov/semester5-lecture-notes.git "$GITHUB_WORKSPACE/deploy"

        # (*) To add a file, add the following command for that file
        cp -f probas/cheatsheet.pdf "$GITHUB_WORKSPACE/deploy/probas_cheatsheet.pdf"
        cp -f probas_full_cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/probas_full_cheatsheet.pdf"
        cp -f probas_amphi/fr/main.pdf "$GITHUB_WORKSPACE/deploy/probas_notes.pdf"
        cp -f optimisation/cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/optimisation_cheatsheet.pdf"
        cp -f optimisation/cheatsheet_full/main.pdf "$GITHUB_WORKSPACE/deploy/optimisation_cheatsheet_full.pdf"

        cp -f ias-cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/ias-cheatsheet-english.pdf"

        cp -f measure-theory/explanations/carathedory-criterion/en/main.pdf "$GITHUB_WORKSPACE/deploy/measure-theory-caratheodory-criterion-en.pdf"
        cp -f measure-theory/explanations/carathedory-criterion/fr/main.pdf "$GITHUB_WORKSPACE/deploy/measure-theory-caratheodory-criterion-fr.pdf"

        cp -f measure-theory/cheatsheet/en/main.pdf "$GITHUB_WORKSPACE/deploy/measure-theory-cheatsheet-en.pdf"
        cp -f measure-theory/cheatsheet/fr/main.pdf "$GITHUB_WORKSPACE/deploy/measure-theory-cheatsheet-fr.pdf"
        cd "$GITHUB_WORKSPACE/deploy"

        git add -A
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
